### ISSUE TITLE
How to get reportOtherOutcome() to trigger so you can test your plugin?

### ISSUE THREAD

**Issue by CleanCut** [nose-devs/nose2#170]
**How can I write a test that causes `reportOtherOutcome()` to be called on the nose2 plugin that I'm working on?**

_I admit this may not be an actual issue, per se, but I have read the documentation, searched the documentation, searched python.org unittest documentation, googled, experimented, and "browsed" the issue list (they ought to let you search issues), and I can't figure this out.  I looked for a mailing list and didn't find one.  So here I am._

**Comment by sirosen** [comment]
Doing a cleanup of old issues; this is still not properly documented.

The only way that `reportOtherOutcome` is triggered is when the reporter gets an event where the result is not recognized. There's no way within nose2 itself to trigger this; it can only happen when another 3rd party plugin is explicitly producing such results.

I think the docs shouldn't try to provide a complete example for such a case, since it's extremely niche and docs would be long and complicated -- they're more likely to confuse users who don't understand what's being documented than actually help anyone. I've put together a doc fix and will consider this closed when that merges.
