### ISSUE TITLE
cProfile support

### ISSUE THREAD

**Issue by peteut** [nose-devs/nose2#226]
The profiling plugin `nose2.prof` does not work w/ recent Python versions, as `hotshot` is no longer available. I've wrote a profiler plugin using `cProfile` [nose2-cprof](https://github.com/peteut/nose2-cprof) as I had to profile my tests. Are there any plans to support `cProfile` in `nose2` anytime soon?
Thanks for this great library!

**Comment by eads** [comment]
I really would like this for http://github.com/newsdev/elex (because the faster you can get election results, the happier everyone is). 

@peteut If you're interested, I'd be happy to go ahead and take your code and prep it for a nose2 pull request. @thedrow still interested in merging this to replace the old profile module?

**Comment by peteut** [comment]
@eads go ahead, I would be really happy to have `cprof` support in `nose2`!

**Comment by thedrow** [comment]
Sure.

**Comment by eads** [comment]
Great. I'll try and roll something after christmas.

On Wed, Dec 23, 2015 at 4:07 AM, Omer Katz <notifications@github.com> wrote:

> Sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nose-devs/nose2/issues/226#issuecomment-166838767>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by little-dude** [comment]
@eads are you still working on this? I'd be interested but I'm currenlty working on other features.

**Comment by eads** [comment]
@little-dude, I haven't had a chance, but I should be able to do it in the
next couple of weeks. We're rolling a new version of our election library
before an election at the beginning of March and I'd like to have this
fixed by then.

On Mon, Feb 22, 2016 at 5:14 AM, little-dude <notifications@github.com>
wrote:

> @eads <https://github.com/eads> are you still working on this? I'd be
> interested but I'm currenlty working on other features.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nose-devs/nose2/issues/226#issuecomment-187107420>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by sirosen** [comment]
This was done in nose2 v0.9.1
