### ISSUE TITLE
"ImportError: No module named xxx.xxx.test_suite" for every test

### ISSUE THREAD

**Issue by dmakhno** [nose-devs/nose2#250]
I'm trying to check nose2 with [this](https://github.com/qubell/contrib-python-qubell-client/tree/master/integration_tests)
But I got: `ImportError: No module named integration_tests.*.test_*` for each test.

Steps:
- `$ pip show nose2`

```
Metadata-Version: 1.1
Name: nose2
Version: 0.4.7
```
- `$ git clone` ...
- `$ cd integration_tests` or even `$ cd qubell/tests`
- `$ nose2`

Actual:

```
ERROR: integration_tests.*.test_* (nose2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: integration_tests.*.test_*
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose2/plugins/loader/discovery.py", line 189, in _find_tests_in_file
    module = util.module_from_name(name)
  File "/Library/Python/2.7/site-packages/nose2/util.py", line 80, in module_from_name
    __import__(name)
ImportError: No module named integration_tests.*.test_*
```

Expected:
No nose2 exception
nosetests - should complain on configuration for `integration_tests`
nosetests - passes for `qubell/tests`

mp-plugin: when I add mp-plugin (`nose2 -N 8`), I got #109, and I have no ideas how to fix it. These are integration tests and have a lot of natural waiting, and expected to be executed in parallel but I don't get how.

What I can do now?

**Comment by dmakhno** [comment]
@thedrow, it this `1.0.0` milestone? 
I'm really stuck with this and cannot try adapting this.

**Comment by thedrow** [comment]
Sorry. I'm no longer actively maintaining the project.

**Comment by little-dude** [comment]
Sorry for hijacking this thread, but there is not IRC/ML for nose2 afaik.

> Sorry. I'm no longer actively maintaining the project.
@thedrow is anyone maintaining this project? It seems that @jpellerin is not working on it anymore.

**Comment by jpellerin** [comment]
I don't believe we have an active maintainer at this time, no. Sorry.

**Comment by little-dude** [comment]
Ok. Anyway it's a cool framework, so thank you for the work you did already. I hope I'll manage to make a few PRs in a near future.

**Comment by sirosen** [comment]
This is an old issue which I just tried looking into, and believe should be closed.

- The issue is 3 years old, and refers to the master branch of another repo, which makes it difficult/impossible to be certain what code was running at the time
- That repo has a `nose` testsuite, and `nose2` is known not to be fully compatible with nose
- Looking at the current `master` for that repo, `nose2` fails in completely unrelated ways
- The original issue doesn't provide sufficient detail (e.g. a minimal example of a failing module) which would let us reproduce, troubleshoot, and fix

All of this is not to cast aspersions and blame: I just don't think it's realistic to expect that we can do anything meaningful with this.
Also, #109 is closed, so we have some related/relevant issue which has been resolved.

I'm closing, but if someone has grounds to reopen, feel free.
