### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by thedrow** [nose-devs/nose2#261]
I no longer have the capacity to maintain the project.
Any volunteers?

**Comment by little-dude** [comment]
I've been using nose2 for more than a year as part of my job, and I'm quite familiar with it now, so I think I could help maintaining it.

**Comment by thedrow** [comment]
@jpellerin Can you please add @little-dude as a maintainer?
I don't have privileges to do so.

**Comment by jpellerin** [comment]
Done. Thanks for all of your work @thedrow and thanks stepping in to help out, @little-dude!

**Comment by little-dude** [comment]
thanks @thedrow and @jpellerin !

**Comment by thedrow** [comment]
:+1: 
I'm going to keep this open to ensure other people join.
@jpellerin Can you please ensure both of us can add other members?

**Comment by warsaw** [comment]
I won't likely be that active because of workload but I've also been using and advocating nose2 for years, and I maintain it in Debian and Ubuntu.  I'd be happy to help out where I can.

**Comment by little-dude** [comment]
I'll close this since it's been two weeks and I could find some time to work on nose2. @warsaw any help would be welcome :) The next steps for me  is to support python 3.5, and then I'll try to close a bunch of issues. I'd like to tackle all the issues related to test loading failures:

https://github.com/nose-devs/nose2/issues/259
https://github.com/nose-devs/nose2/issues/250
https://github.com/nose-devs/nose2/issues/214 (although this one does not really look like a bug to me)
https://github.com/nose-devs/nose2/issues/109 (pretty bad)
https://github.com/nose-devs/nose2/issues/53 (this one is super annoying)
