### ISSUE TITLE
coverage: fail_under and non-zero exit code

### ISSUE THREAD

**Issue by carldunham** [nose-devs/nose2#285]
I may be doing something wrong, but it looks like the `fail_under` param in coverage is not being respected by nose2. I have this set to 100, but still get a zero return code from nose2.

For CI, etc., it would be helpful to see a non-zero return code for inadequate coverage.

**Comment by rzilleruelo** [comment]
@carldunham did you find any solution for this?

**Comment by sirosen** [comment]
Now that we're on `coverage` rather than `cov-core`, I'm looking at this, and I think this is potentially a pretty easy feature.
`Coverage.report` returns a % covered, and you can get at this config value with `Coverage.get_option("report:fail_under")`

Compare, and _voila_ you have the `fail_under` result.

I'm not sure how to get the desired exit behavior though. Will investigate.
