### ISSUE TITLE
nose.tools.set_trace

### ISSUE THREAD

**Issue by delfick** [nose-devs/nose2#303]
Hello,

I was just wondering if there is an equivalent to nose.tools.set_trace in nose2, so that I can still run a pdb debugger when I have the output-buffer plugin enabled?

Thanks

**Comment by alexandrebarbaruiva** [comment]
so, is there an equivalent after all?

**Comment by delfick** [comment]
oh wow, I made this ticket a long time ago.

I now use pytest everywhere and in pyest you just use pdb.

**Comment by alexandrebarbaruiva** [comment]
Oh, ok, thanks!

**Comment by sirosen** [comment]
I'm reviewing old issues and I'm going to close this due to our limited availability to work on fixes and the fact that there are viable workarounds for nose2 users.

If you are still using nose2, you can either use the debugger plugin to open pdb on test failure or use a plan pdb `set_trace` call and turn off any use of output buffering.

As noted by the OP, combining output buffering and `set_trace` doesn't work, but I'm comfortable living with that limitation. If someone comes across this issue and those workarounds aren't sufficient either, I'd appreciate hearing more about the use-case so that we can think about an appropriate way of handling it.

Two brief asides:
1. Even as a nose2 maintainer, I'm a big fan of pytest. If it works for you, I say go for it! We'll still be here maintaining this project for those who need it.
2. Sorry this issue sat so long without attention! A lot of nose2 issues have been left sitting. I'm trying to rectify that and get on top of our issue backlog.
