### ISSUE TITLE
Provide more useful message about missing `coverage-plugin`

### ISSUE THREAD

**Issue by nhooey** [nose-devs/nose2#355]
When I invoke `nose2 --with-coverage` when `nose2` and `coverage` are installed, I get this unhelpful error message:

```
$ nose2 --with-coverage
Warning: you need to install [coverage-plugin] extra requirements to use this plugin
```
This message would be more helpful if it included instruction son how to install `coverage-plugin`, or what parameters to load it.

The [Test coverage reporting](http://nose2.readthedocs.io/en/latest/plugins/coverage.html) section of the nose2 documentation doesn't mention the need to install `coverage-plugin`, or how to install it, so it looks like the documentation is incorrect.

That documentation also implies that `coverage-plugin` is loaded by default, given that it appears in the [Built-in and loaded by default](http://nose2.readthedocs.io/en/latest/plugins.html#built-in-and-loaded-by-default) section.

**Comment by nhooey** [comment]
In my particular case, the coverage plugin is seemingly present:
```
.venv/lib/python3.6/site-packages/nose2/plugins/coverage.py
```
Where that virtualenv has been activated with `source .venv/bin/activate`.

**Comment by katrinabrock** [comment]
@sirosen You know more about this than I do. Is this still an issue after your changes?

**Comment by sirosen** [comment]
> Is this still an issue after your changes?

Actually, I think I may have made it slightly worse.
Part of the issue here is that the docs for `latest` on readthedocs now state that you need to install `coverage`, but the last release still needs `cov-core`. I'll open a PR to change it back, since `nose2[coverage-plugin]` will work for all versions.

@nhooey, [`nose2[coverage-plugin]` specifies `coverage>=4.4.1`](https://github.com/nose-devs/nose2/blob/b5eeeba68f2bad3e199af8903cdd0540b95f06cf/setup.py#L51-L53) , but until only a couple of days ago [it specified `cov-core>=1.12`](https://github.com/nose-devs/nose2/blob/f9851a2841b21b4abe98d52b0928700b28aaf937/setup.py#L51-L53). It's probably best to just install `nose2[coverage-plugin]` and let it specify which dependency to install.
I'll improve the error message about this in my PR too; the message isn't great for users unfamiliar with extra requirements.

> The Test coverage reporting section of the nose2 documentation doesn't mention the need to install `coverage-plugin`, or how to install it, so it looks like the documentation is incorrect.

As mentioned, it's correct for the latest version of the code. The upcoming fix should make it correct for all versions.

> That documentation also implies that `coverage-plugin` is loaded by default, given that it appears in the Built-in and loaded by default section.

It is loaded by default, and the _plugin_ part of it is built-in, but it has an optional dependency.
I think documenting the dependency and improving the warning message are the best path forward.
