### ISSUE TITLE
Update the README/Community Discussion/Existential Crisis

### ISSUE THREAD

**Issue by katrinabrock** [nose-devs/nose2#361]
I don't think we can really say that folks reading the readme these days are

> witnesses at the new birth of nose, mark 2

Most of the other info there is also false.

I am hereby opening the discussion on where are we and where are we going?

Specifically:
* Would we actually recommend people use nose2 over pytest for new projects?
* If so why?
* If not, what is the role of this project?
* Do we want to stabilize to a 1.0.0 at some point? If so, what needs to happen before we get there?

**Comment by sirosen** [comment]
> - Would we actually recommend people use nose2 over pytest for new projects?
> - If so why?

Doing so would demand some rationale. We have to be honest with ourselves about the facts that
- there's nothing that `nose2` can do that `pytest` cannot do
- the development community is a lot larger and more active around `pytest` and its plugins.

`Such` was a cool idea, and I have a project making heavy use of Layers to get more layers of setup/teardown than I could with unittest, but it's hard to make a case for using those tools over [pytest fixtures](https://docs.pytest.org/en/latest/fixture.html).

> - If not, what is the role of this project?

*shrugs*
Bugfixes and maintenance for those still using it, and accepting new features if anyone wants to add value to projects already using `nose2`.

> - Do we want to stabilize to a 1.0.0 at some point? If so, what needs to happen before we get there?

The traditional [semver advice would suggest that nose2 should release 1.0](http://semver.org/#how-do-i-know-when-to-release-100).
Given the amount of discussion and testing in Gitter prior to releasing `0.7.0`, it seems like the mentality of not wanting to break people's builds is already there.

**Comment by katrinabrock** [comment]
I agree with @sirosen response to nose2 vs pytest. 

Follow up question: what about nose2 vs nose?

Seems like there are enough of us where our companies are basically locked in to nose2 that there is capitalist interest in keeping it minimally maintained even if it is not competitive with pytest. Is the same true for nose? If not, that alone is an advantage and moving from nose to nose2 is going to be much easier than moving from nose to pytest. We can make an effort to make it even easier than it is today.

**Comment by sirosen** [comment]
> moving from nose to nose2 is going to be much easier than moving from nose to pytest

I'm not sure that this is true today, but it sounds like you're saying we could make it a priority to make it easier to go `nose -> nose2` than `nose -> pytest`? It's a way to differentiate the project, at least.

Some cases might be quite easy, too (e.g. small compatibility features like `nose.tools.istest` -> `nose2.tools.istest`), which may make this attractive.

> Is the same true for nose?

The prospect of working on, and cutting new releases of, nose is somewhat scary. Its code is older, and used by a much larger audience than nose2 on a generally older generation of interpreters. The possibility of introducing incompatibilities, especially on non-modern pythons like 2.6, is therefore naturally higher. It also has a harder py2+py3 support path, using `2to3`.

It's been 2 years since the last commit to nose's `master` branch, and I think it's effectively being phased out from most projects.

In general, I would only attempt to make commits to `nose` to perform absolutely critical maintenance which cannot be avoided.
That's somewhat different from `nose2`, which (for now at least) we seem to be comfortable modifying.

**Comment by ptthiem** [comment]
Honestly, what does pytest have for layers?  I'm pretty sure that I'm making some use of layers in some fairly non-trivial ways.  But I haven't had to touch the base code for so long...

**Comment by ptthiem** [comment]
Taking a quick look.   I see they have a temp directory plug in, I had to implement one of those.  Junit XML is important.  I see they have something for static code analysis, but I have Jenkins extract those reports separately because I want the breakdowns for those...

**Comment by sirosen** [comment]
> what does pytest have for layers?

The base functionality in pytest fixtures is not _quite_ the same, but it's close for a number of use-cases. There are cases which are non-trivial to represent with pytest fixtures, but I can't think of any which are sufficiently hard that they'd be persuasive.

Some of the highlights that convinced me (and make pytest attractive, personally, for future projects):
- [Fixtures can use one another](https://docs.pytest.org/en/latest/fixture.html#modularity-using-fixtures-from-a-fixture-function), which gives the core "layering" functionality
- [Session scoped fixtures](https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session) can be used like top-level layers for all of your tests.
- [The use of fixtures as context managers](https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code) can replace testSetUp/testTearDown

**Comment by SalmonMode** [comment]
> what does pytest have for layers?

If it helps anyone who uses `Such`, I made (and am still adding to) a tool called [Contextional](https://github.com/SalmonMode/contextional) after I saw `Such` because I wanted similar functionality but I thought `nose2` was no longer under development. The goal is for it to work in any testing framework.

So if you do need to switch away from `nose2` and you used `Such`, there's at least one alternative for you to use.

Having said that, I will definitely be supporting `nose2` with Contextional.
