### ISSUE TITLE
[Debian] Can you help me with providing a description for the package?

### ISSUE THREAD

**Issue by P-EB** [nose-devs/nose2#379]
Hey,

Me again, with a simple query this time.

The current descriptions of nose2 packages are really short and non-explicit.

I'd like to fix that. For this, I'd need a descriptive paragraph (400 chars max) that describes properly what is nose2 and what purpose it serves.

I tried this, but it looks too generic and a bit short.

```
Nose2 is a testsuite framework that extends the features provided
by unittest in order to make testing easier and more plugin-compliant.
```

Can you help me putting this in good words?

Cheers.

**Comment by katrinabrock** [comment]
If this is for a system level package, maybe specify that it's a python tool. Maybe instead of `plugin-complient` something along the lines of `provides an easy to use plugin API and built-in plugins for common scenarios`. Maybe even mention a few of the built in plugins? MP, layers, and junitxml seem to have the most interest, don't know if that's because they're the most used or the most buggy :-P.

**Comment by P-EB** [comment]
Hey,

Yes, it's a distro-package. :)

The package name is python-nose2/python3-nose2, so mentioning that it's Python is possible but not mandatory.

Do you have an example of paragraph you'd suggest?
