### ISSUE TITLE
Changing output of --verbose to be cleaner

### ISSUE THREAD

**Issue by Singletoned** [nose-devs/nose2#385]
The output of running `nose2 -v` was a little surprising to me.

Expected:
```tests.test_utils.test_listify ... ok```

Outcome:
```test_utils.transplant_class.<locals>.C (test_listify) ... ok```

Is this the intended output?  If so, how hard would it be for me to change to something more like what was in Nose 1?  I'd be happy to write a plugin that does it, if I can get a few pointers in the right direction.

Thanks

Ed

**Comment by sirosen** [comment]
Hi Ed. Sorry it's taken so long for anyone to get back to you on this.

This is a change in `unittest2` behavior which `nose2` is also getting (a lot of `nose2` code is forked `unittest2` code).
Under python3.5+, `unittest2` test names include the fully-qualified classname. It's less ambiguous this way... but I agree that it looks funky.
You can get similar behavior with `python3 -m unittest discover -v`, using `load_tests`.

So, yes, this output is intentional.

There's a [comment in the nose2 testsuite about this](https://github.com/nose-devs/nose2/blob/88052d1af381bbd7cd402ba3282266fdc6b35b04/nose2/tests/functional/test_loadtests_plugin.py#L30-L33), actually.
The test case it's describing is [here](https://github.com/nose-devs/nose2/tree/master/nose2/tests/functional/support/scenario/load_tests_pkg), and you can actually run `nose2 -v` there to see that it has the same behavior you're describing.

In this scenario, we're generating a test class inside of a function, which is why it has the `<locals>` as part of its fully qualified name.
Is your testsuite doing something similar?

---

If you wanted to avoid this, you *could* add an option to the nose2 loadtests plugin which always uses the python<3.5 output style. That would probably be a more fruitful path than trying to a separate plugin because it would have to get in the mix with the test loader pretty deeply. It will not be a *big* change, but it will be difficult/delicate.

TBH, I don't think it's worth it -- the `unittest2` maintainers thought this was a good change, and it's easier to trust them than to go it alone.

If you're certain you want to do this, I'm willing to review it, provided you add tests for it to make sure it behaves correctly.
Good naming is hard, but `loadtests.oldstyle_testnames=True` seems a pretty reasonable parameter name.

**Comment by sirosen** [comment]
Closing as a wontfix. I grant that the behavior might be surprising or even considered "weird", but it comes from a sensible place.

**Comment by wittlesouth** [comment]
Found this today. I'd prefer not to see a non-useful message in the verbose output, and find the decision not to at least have a documented config option to control this curious.

I've brute-forced a dumb solution that make work for others:

`nose2 -v 2>&1 | grep -v "transplant_class"`

This removes the transplant class lines from the verbose output without requiring a new plugin or changes to the existing plugin. I'm sure it has potential side effects as a broad solution, but works fine for my use case.
