### ISSUE TITLE
Missing assert_raises ?

### ISSUE THREAD

**Issue by Aletz-Arce** [nose-devs/nose2#471]
Hi everyone,
How to import/use assert_raises  nose2.
Regards

**Comment by sirosen** [comment]
There is no method named `assert_raises` anywhere in `nose2` or, as far as I know, in `unittest`.
Since `nose2` tests inherit properties from `unittest.TestCase`, you should be able to use `assertRaises`.
You can see details on how to use `assertRaises` [in the documentation for unittest](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises).

As I don't think there's a bug or documentation issue for `nose2` to tackle here, I'm going to close this.
