### ISSUE TITLE
--junit-xml-path does not generate the result xml file

### ISSUE THREAD

**Issue by WMvmane** [nose-devs/nose2#521]
When using nose2 command with command line parameter to generate am output junit xml file with a specific name does not seem to work. I am using the following command:
nose2 --plugin=nose2.plugins.mp -N 3 -c nose2.cfg --plugin=nose2.plugins.junitxml --junit-xml-path='C:\QATest\results\result202207121924.xml' does not seem to generate any result xml file.

**Comment by sirosen** [comment]
I will try to make sure I remember to look into this soon to see if I can reproduce.

If you are able to produce one, it would be helpful to have a complete [MWE](https://stackoverflow.com/help/minimal-reproducible-example) to be able to dive into this quickly and easily.

I wouldn't be entirely surprised if `--plugin=nose2.plugins.junitxml --junit-xml-path=...` doesn't behave correctly but putting the plugin declaration into your config file _does_ work. But before accepting this as a bug, I need to reproduce it.

**Comment by WMvmane** [comment]
Do you mean to say that I should configure the plugin declaration in the config file and just use --junit-xml-path as a command line parameter to pass the filename at runtime?

**Comment by sirosen** [comment]
I just went to reproduce this and I realized what the issue is! You're missing `--junit-xml` as an argument. You need that in addition to `--junit-xml-path=...`. (I'm not defending that behavior, but that's how it works today.)

Sorry about that -- it's confusing.

I'm going to keep this open because I'd like to look at changing things so that `--junit-xml-path` implies `--junit-xml`. I'll have to get into this sometime soon to see how easy/hard that is to change.

**Comment by WMvmane** [comment]
Ok. No problem. Do I need to pass any value to the parameter `--junit-xml`  ?

**Comment by sirosen** [comment]
This is fixed and it will make it out in the next release. I was hoping to get to that today, but I got stymied with some other issues. It will be available soon though. `--junit-xml-path` will start to imply `--junit-xml` so that you don't need both options.
